development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ridbuk_development
  pool: 5
  username: rails_user
  password: mint06

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ridbuk_test
  pool: 5
  username: rails_user
  password: mint06

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ridbuk_production
  pool: 5
  username: rails_user
  password: mint06 
